### ISSUE TITLE
Heptio Ark is now Velero

### ISSUE THREAD

**Issue by rosskukulinski** [openebs/velero-plugin#1]
Hi!  Thanks for creating a plugin for Ark.

I wanted to give you a heads up that today we announced the rename of the project: https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/.

The Velero team is working on a 0.11 release which will complete the code- and plugin-related changes to complete the rebranding.

We'd also be happy to add you the list of [community plugins](https://github.com/heptio/velero/blob/master/docs/support-matrix.md) when you're ready to announce your plugin to the larger Ark community.

Let me know if you have any questions!

**Comment by mynktl** [comment]
Hi @rosskukulinski 
Thanks for the update. We have released our velero-plugin and also added to velero community plugin list.
