### ISSUE TITLE
DisableSSL option not working

### ISSUE THREAD

**Issue by LennertMertens** [openebs/velero-plugin#113]
**What steps did you take and what happened:**

Our S3 bucket has a self signed certificate, we have the CA, but we are not able to supply it (I don't see any options to do this). The `DisableSSL` option that seems to be available also doesn't seem to do anything.

**What did you expect to happen:**

Expected that the volumes would be backup up, instead we got the following error:

```
time="2020-09-11T12:23:04Z" level=error msg="Failed to close cloud conn : blob (key \"backups/backuptest/cstor-pvc-bcd7025b-a0ba-11ea-b95b-005056ab875a-backuptest.pvc\") (code=Unknown): RequestError: send request failed\ncaused by: Put \"https://OURBUCKET\": x509: certificate signed by unknown authority" backup=velero/backuptest cmd=/plugins/velero-blockstore-cstor logSource="/home/travis/gopath/src/github.com/openebs/velero-plugin/pkg/clouduploader/operation.go:108" pluginName=velero-blockstore-cstor
time="2020-09-11T12:23:04Z" level=info msg="1 errors encountered backup up item" backup=velero/backuptest logSource="pkg/backup/backup.go:444"
```

**Environment:**
- Velero version (use `velero version`): 1.4.2
- Velero-plugin version: 1.12
- OpenEBS version: 1.10.0
- Kubernetes version (use `kubectl version`): 3.11

**Comment by GBrawl** [comment]
As a workaround we fixed this by just mounting the cert in the /etc/ssl/certs directory in the velero pod.

**Comment by mynktl** [comment]
Thanks for the workaround @GBrawl.

Hi @LennertMertens ,`DisableSSL` won't work if minio is configured with custom certificate. To access TLS secured minio, Plugin needs to have certificate data or plugin can skip certificate verification. As of now plugin doesn't have support of this.
