### ISSUE TITLE
Question related to BackupStorageLocation for on-prem

### ISSUE THREAD

**Issue by cormachogan** [openebs/velero-plugin#15]
Hi @mynktl,

At the moment, the supported BackupStorageLocation states that there is only support for AWS and GCP. Do you have any plans to support an on-prem BackupStorageLocation, such as an S3 Object Store provided by Minio? In other words, could the OpenEBS CStor plugin send the volume backup blocks to the same location (on-prem) that Velero sends the metadata about the Pods/PVs/PVCs/STS etc to?

Thanks

**Comment by vishnuitta** [comment]
Thanks @cormachogan for this feature request.
This is fixed with this PR: https://github.com/openebs/velero-plugin/pull/16

**Comment by muratkars** [comment]
Hi @cormachogan pleasure to see you here.
This is addressed in the latest [0.9](https://github.com/openebs/openebs/releases/tag/0.9) release. 
Let us know if this resolves your issues.
