### ISSUE TITLE
OpenEBS Local PV Hostpath

### ISSUE THREAD

**Issue by cleveritcz** [openebs/velero-plugin#165]
Hello,
could you create the plugin for OpenEBS Local PV Hostpath, please? 

I saw velero is supported but can't find correct OpenEBS provider for velero.

**Comment by mynktl** [comment]
Hi @cleveritcz 
Since openebs local PV is file base volume, you can use [Valero's restic integration](https://velero.io/docs/v1.6/restic/#docs) to backup OpenEBS local PV hostpath.

I'm closing this issue for now. Feel free to reopen if required.

Thanks.
