### ISSUE TITLE
[feat request] native zfs snapshots during backup

### ISSUE THREAD

**Issue by jr0dd** [openebs/velero-plugin#176]
This is feature request for my original issue https://github.com/openebs/velero-plugin/issues/175#. 

I would love to have the ability to automate local native ZFS snapshots for the PVC's that Velero is backing up. It allows for simple and quick rollbacks ZFS style if ever needed on a single volume. It would also allow ZFS snapshots to be taken more gracefully than using the underlying OS to take snapshots. In addition, it would be great to have snapshots pruned according to the ttl in the backup schedule.

**Comment by ianb-mp** [comment]
What happened to this - was it implemented?
