### ISSUE TITLE
Possibility to rename api server service

### ISSUE THREAD

**Issue by walnuss0815** [openebs/velero-plugin#20]
Hi!

When I try to do a backup from a testing deployment (MySQL server with PV) the following error occours:

```
time="2019-07-07T12:46:03Z" level=info msg="Initializing velero plugin for CStor map[s3Url:http://minio.velero.svc:9000 DisableSSL:true bucket:velero-test prefix: provider:aws region:minio s3ForcePathStyle:true]" backup=velero/defaultbackup7 cmd=/plugins/velero-blockstore-cstor logSource="/home/travis/gopath/src/github.com/openebs/velero-plugin/pkg/snapshot/snap.go:36" pluginName=velero-blockstore-cstor
time="2019-07-07T12:46:03Z" level=error msg="Error getting IP Address for service{maya-apiserver-service} : services \"maya-apiserver-service\" not found" backup=velero/defaultbackup7 cmd=/plugins/velero-blockstore-cstor logSource="/home/travis/gopath/src/github.com/openebs/velero-plugin/pkg/cstor/cstor.go:139" pluginName=velero-blockstore-cstor
time="2019-07-07T12:46:03Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/defaultbackup7 error="rpc error: code = Unknown desc = Error fetching OpenEBS rest client address" error.file="/home/travis/gopath/src/github.com/openebs/velero-plugin/pkg/cstor/cstor.go:166" error.function="github.com/openebs/velero-plugin/pkg/cstor.(*Plugin).Init" group=v1 logSource="pkg/backup/item_backupper.go:410" name=pvc-6319d404-a0ab-11e9-9f37-000c298d4a86 namespace=default persistentVolume=pvc-6319d404-a0ab-11e9-9f37-000c298d4a86 resource=pods volumeSnapshotLocation=default
time="2019-07-07T12:46:03Z" level=info msg="Persistent volume is not a supported volume type for snapshots, skipping." backup=velero/defaultbackup7 group=v1 logSource="pkg/backup/item_backupper.go:430" name=pvc-6319d404-a0ab-11e9-9f37-000c298d4a86 namespace=default persistentVolume=pvc-6319d404-a0ab-11e9-9f37-000c298d4a86 resource=pods
```

I am using K8s On-premises and successfully installed OpenEBS using the Helm Chart. It looks like the name of the maya api server is fixed to [maya-apiserver-service](https://github.com/openebs/velero-plugin/blob/940d372de849e16a41285373f104644810fd967b/pkg/cstor/cstor.go#L46) and in the Helm Chart it is set to [{{ template "openebs.fullname" . }}-apiservice](https://github.com/helm/charts/blob/master/stable/openebs/templates/service-maya-apiserver.yaml#L4). So is there a possibility to set the name in the Velero plugin manually without creating an renamed copy of the api server service?

**Comment by jadsy2107** [comment]
Im still getting this error
time="2022-11-16T01:34:32Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/npm error="rpc error: code = Unknown desc = Error fetching OpenEBS rest client address" error.file="/home/travis/gopath/src/github.com/openebs/velero-plugin/pkg/cstor/cstor.go:192" error.function="github.com/openebs/velero-plugin/pkg/cstor.(*Plugin).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-e383c200-6da8-416b-95c0-a6365eaa7961 namespace= persistentVolume=pvc-e383c200-6da8-416b-95c0-a6365eaa7961 resource=persistentvolumes volumeSnapshotLocation=default
