### ISSUE TITLE
Velero Restore not possible because of psp.

### ISSUE THREAD

**Issue by amarshaw** [openebs/velero-plugin#23]
As per the velero restore steps we need to exec into the cstor pods to set service IP.
In our infractore psp is enabled and its not allow exec in privileged container.

With the currect process we cant restore velero backup.

Error:

kubectl -n openebs exec -it cstor-01w9-6d4b8f8cf4-t5rgf -c cstor-pool -- bash
Error from server (Forbidden): pods "cstor-01w9-6d4b8f8cf4-t5rgf" is forbidden: cannot exec into or attach to a privileged container

**Comment by mynktl** [comment]
Hi @amarshaw, Thanks for raising the issue.
We are  tracking this issue in our release plan. This issue will be fixed in upcoming release(~1.2).

**Comment by mynktl** [comment]
cc: @ajeshbaby

**Comment by mynktl** [comment]
Hi @amarshaw 
I'm closing this issue since it has been fixed in a release 2.4.0. Reference PR #131.
If you have more issues, please feel free to reach out.

Thanks.
