### ISSUE TITLE
Incremental backups and CStorBackup/CStorCompletedBackup resources

### ISSUE THREAD

**Issue by ivanfilippov** [openebs/velero-plugin#37]
Hi there!

Thank you for building this plugin, it's great!

Through my testing I ended up with two questions:

- How do I perform a restore when the first backup (the initial full) reaches its TTL and is cleaned up/deleted by Velero? I'm referring to the incremental backup section of the README.

- In my limited testing it doesn't look like the plugin cleans up the CStorBackup/CStoreCompletedBackup resources in k8s (I'm not sure how to check whatever objects remain within OpenEBS, but I'm assuming they are not cleaned up either). Is this a planned feature or do I need to clean these up manually/via script?

**Comment by mynktl** [comment]
Hi @ivanfilippov 
Thanks for trying out the plugin.

1. If your base-backup(or first backup) is deleted then you won't be able to restore the volume.
2. `CStorBackup/CStoreCompletedBackup` are used for incremental backup functionality. If you delete it then scheduled snapshot won't work as expected. 

Please let me know if you have any more doubts
Thanks!

**Comment by ivanfilippov** [comment]
Thank you for the reply!

Is your recomendation then to set a very high TTL for velero backups so the base-backup does not expire?

**Comment by mynktl** [comment]
yes @ivanfilippov 

Sorry for late reply. I completely missed tracking this issue.

Recently we are working on a solution to tackle this issue with base-backup, where you won't have a long list of incremental backup -- this will save the restore time and also storage space. 

Please let me know if you are having any issue/limitation with backup/restore.
Thanks

**Comment by mynktl** [comment]
Closing this out as inactive - feel free to reach out again as needed.
