### ISSUE TITLE
Velero 1.2 will be supported?

### ISSUE THREAD

**Issue by SVronskiy** [openebs/velero-plugin#45]
Are you planning to support [Velero release 1.2.0](https://github.com/vmware-tanzu/velero/releases/tag/v1.2.0)?

Velero-plugin was not mentioned at [Roadmap for 1.5 and later](https://www.cncf.io/webinars/kubernetes-storage-is-more-than-csi-do-it-right-the-openebs-way/) at all.

**Comment by SVronskiy** [comment]
I experience probem with installing Velero 1.0 on on-premises k8s 1.16. When I installing Velero 1.1, I experience problem with cStor backup.

**Comment by SVronskiy** [comment]
Closing issue, everything is Ok. Later will PR sample yamls to backup OpenEbs 1.4 with Velero 1.2 - it was not obvious.

**Comment by tux-00** [comment]
I'm experiencing issues during backup of cstor storage on kubernetes 1.16, openebs 1.5 and velero 1.2. Can you confirm that velero 1.2 is working on your side ? @SVronskiy

**Comment by SVronskiy** [comment]
Hello, @tux000! I have no problems with backup, but have problem with restore of cstor data, 1.17/1.5/1.2 on my end, currently researching issue.

What problem do you have?

Have you tried [Vito script](https://github.com/vitobotta/velero-openebs-backup)?

**Comment by SVronskiy** [comment]
@tux-00

**Comment by tux-00** [comment]
Finally working, I was including openebs velero plugin docker as init container, thinking that velero on kubernetes need it to work properly. But it's OK I think you can close :)
