### ISSUE TITLE
Unable to install velero plugin

### ISSUE THREAD

**Issue by snyamars** [openebs/velero-plugin#51]
Hi,
I have setup OpenEBS as per the documentation. Now I am trying to install velero-plugin as per the documentation.Using the following instruction:
velero install \
    --provider aws \
    --plugins openebs/velero-plugin:ci \
    --bucket busybox \
    --secret-file secret-file \
    --use-volume-snapshots=false \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://<<ipaddress:port>>,publicUrl=http://<<ipaddress:port>>

Getting the following error:
level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413" An error occurred: some backup storage locations are invalid: error getting backup store for location "default": unable to locate ObjectStore plugin named velero.io/openebs

Velero version: 1.2
OpenEBS: 1.6
OS: Ubuntu 18.04

Pls help.

**Comment by snyamars** [comment]
I am able to get it working with Velero 1.1 version. Looks like some additional changes are required with  1.2 version of Velero.

**Comment by mynktl** [comment]
```
velero install
--provider aws
--plugins openebs/velero-plugin:ci
--bucket busybox
--secret-file secret-file
--use-volume-snapshots=false
--backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://<ipaddress:port>,publicUrl=http://<ipaddress:port>```

openebs.io/velero-plugin is for creating backup of cStor volumes so you need to set `--use-volumesnapshots=true`. For this plugin, provider is `openebs.io/cstor-blockstore` not aws.

**Comment by mynktl** [comment]
For volumesnapshotter, in our case it is openebs.io/cstor-blockstore, you need to follow addition step which is mentioned at https://github.com/openebs/velero-plugin#installation-of-velero-plugin

**Comment by snyamars** [comment]
Thanks Mayank. When I tried with provider as openebs.io/cstor-blockstore, I am getting similar error as shown below:
level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": unable to locate ObjectStore plugin named openebs.io/cstor-blockstore

Note that I am using Velero 1.2 version with the above plugin.  I have created the volume snapshot as suggested in the installation section of velero plugin.

**Comment by mynktl** [comment]
yes, because `openebs.io/cstor-blockstore` is volumesnapshotter.
You need to install velero and backupstoragelocation in first step, which you can do through cli. In second step you need to install the plugin.
1. To install velero with backupstoragelocation aws:
```
velero install
--provider aws
--plugins velero/velero-plugin-for-aws:v1.0.0 
--bucket busybox
--secret-file secret-file
--backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://<ipaddress:port>,publicUrl=http://<ipaddress:port>
```
2. To install plugin
```
velero plugin add openebs/velero-plugin:ci
```
And then install volumesnapshotlocation :
```
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: aws
  namespace: velero
spec:
  provider: openebs.io/cstor-blockstore
  config:
    bucket: busybox
    provider: aws
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://<ipaddress:port>
```

**Comment by snyamars** [comment]
Thanks Mayank. I am able to install the plugin and take backup onto S3 bucket.
When I am trying to restore the backup I am getting the following error:

Normal   Scheduled    4m12s  default-scheduler        Successfully assigned test/busybox-67468c7fd4-kjqdm to ip-172-31-7-81
  Warning  FailedMount  2m9s   kubelet, ip-172-31-7-81  Unable to attach or mount volumes: unmounted volumes=[demo-vol11], unattached volumes=[default-token-bdchc demo-vol11]: timed out waiting for the condition
  Warning  FailedMount  12s    kubelet, ip-172-31-7-81  MountVolume.WaitForAttach failed for volume "pvc-63b27baf-8fad-4840-9616-ad9c5a144384" : failed to get any path for iscsi disk, last err seen:
iscsi: failed to attach disk: Error: iscsiadm: Could not login to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-63b27baf-8fad-4840-9616-ad9c5a144384, portal: 10.96.239.58,3260].
iscsiadm: initiator reported error (8 - connection timed out)
iscsiadm: Could not log into all portals
Logging in to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-63b27baf-8fad-4840-9616-ad9c5a144384, portal: 10.96.239.58,3260] (multiple)
 (exit status 8)

Is there anything I am missing here? I am trying to restore onto the same cluster from where I had taken back of an application earlier.

**Comment by mynktl** [comment]
1. Did you delete old PVC and restored the backup or you are restoring into a different namespace?
2. Did you set targetip? If not then you need to set targetip for the volume in pool pod. Steps to update targetip is as follow:
```
1. kubectl exec -it <POOL_POD> -c cstor-pool -n openebs -- bash
2. zfs set io.openebs:targetip=<PVC SERVICE IP> <POOL_NAME/VOLUME_NAME>
```

**Comment by snyamars** [comment]
I am deleting the old PVC (including the namespace) and then restoring it back.
I am not aware of the targetip. 
I do see that there are multiple PVC services.
admission-server-svc, pvc-109d9633-2e1e-4e8a-8d99-6a37b494d87d,pvc-52f89038-4052-43da-a886-2fa4f4aad1f1,pvc-67d4eb98-10c7-45b6-a9ae-708111b7c9a7. 
Which PVC service should I use?

**Comment by mynktl** [comment]
Name of the PVC service is same as PV name.

**Comment by snyamars** [comment]
Thanks Mayank. I am able to restore the application. However, the overall process of adding targetip based on PVC name seems to be error prone and cumbersome.. Is there a way to automate this step without logging into the container? Do i need to follow the same approach every time I restore a different app?

**Comment by mynktl** [comment]
Hi
I am glad that it is working for you.
For automate process you may check Data Agility platform, called [OpenEBS Director](https://account.mayadata.io/login), which have [DMaas service](https://help.mayadata.io/hc/en-us/articles/360033401591-DMaaS) to backup the application workload.

**Comment by mynktl** [comment]
Hi @snyamars 
I am closing this issue. Feel free to re-open it if you have any issue.
Thanks!

**Comment by cortopy** [comment]
@snyamars how did you manage to do this. 
@mynktl  I'm also struggling and find the instructions a bit cryptic 

I've created the remote backup and restored it. The pvc and pv get recreated ok. The pv gets a status of bounded

Whenever I try to change the target ip I get something like `cannot open 'cstor-loop-pool-7zmx/pvc-f0706f8d-30ca-40b2-9fd6-78de3d940239': dataset does not exist`

I gather I need three things:
- volume name: in my case `pvc-f0706f8d-30ca-40b2-9fd6-78de3d940239`
- service cluster ip for the service with the same name as the volume
- the cstor pool name. This one confuses me, as I have two cstor pools (replication enabled): `cstor-loop-pool-7zmx` and `cstor-loop-pool-job6`

So I have tried many combinations. In the pod `cstor-loop-pool-7zmx-64865588b4-vlpvh` I've tried:

- `zfs set io.openebs:targetip=10.96.86.17 cstor-loop-pool-7zmx/pvc-f0706f8d-30ca-40b2-9fd6-78de3d940239`
- `zfs set io.openebs:targetip=10.96.86.17 7zmx/pvc-f0706f8d-30ca-40b2-9fd6-78de3d940239`
- `zfs set io.openebs:targetip=10.96.86.17 pvc-f0706f8d-30ca-40b2-9fd6-78de3d940239`

I've tried all these combinations in the two cstor pods, each time changing the cstor pool name to the one that matches the pool for that pod

**Comment by snyamars** [comment]
Hi, 
Presume you were able to log into the right container.
kubectl get pod -n openebs | grep cstor-disk-pool
ex the output: 
cstor-disk-pool-1so3-5b7f5cb9d8-qxw4t                             3/3     Running
kubectl exec -it cstor-disk-pool-1so3-5b7f5cb9d8-qxw4t -c cstor-pool -n openebs -- bash
Once logged into the container, execute the following
### zfs list
you will see a list of PVCs
From the above list of PVCs refer the PVC that was bound to the restored application
### zfs set io.openebs:targetip=10.104.29.98 cstor-5ff84b35-e4aa-4d13-a40b-63dac50c26fd/pvc-72514d6e-3acf-42f6-9660-9b790e2ad0b8
--------
Hope this helps

**Comment by mynktl** [comment]
@cortopy It seems your are using wrong pool name. you can get the pool name using `zfs list` as @snyamars mentioned.
You should see something like below:
```
~$ kubectl get pods -n openebs 
NAME                                                              READY   STATUS    RESTARTS   AGE
cstor-pool-mx1h-5475cb44b5-bmn6d                                  3/3     Running   0          70s
maya-apiserver-79f4f7b78d-wzxzj                                   1/1     Running   2          99s
openebs-admission-server-76f54b9df7-z4j48                         1/1     Running   0          99s
openebs-localpv-provisioner-848679fb95-xlf9g                      1/1     Running   0          99s
openebs-ndm-operator-67bfbc6fc7-nxtps                             1/1     Running   1          99s
openebs-ndm-zsjlr                                                 1/1     Running   0          99s
openebs-provisioner-67ffd7b5f9-pd7hg                              1/1     Running   0          99s
openebs-snapshot-operator-6c8b9cf76-h9bkt                         2/2     Running   0          99s
pvc-bea6c119-7abc-478a-a680-bc5a3db180ec-target-75b5ff55cdqljhq   3/3     Running   1          12s
~$ kubectl exec -it cstor-pool-mx1h-5475cb44b5-bmn6d -n openebs -ccstor-pool -- zfs list 
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
cstor-1d7bf36e-944f-447b-b27b-e3f7c4df7222                                            263K  9.63G   512B  /cstor-1d7bf36e-944f-447b-b27b-e3f7c4df7222
cstor-1d7bf36e-944f-447b-b27b-e3f7c4df7222/pvc-bea6c119-7abc-478a-a680-bc5a3db180ec     6K  9.63G     6K  -
```
In above example pool name is `cstor-1d7bf36e-944f-447b-b27b-e3f7c4df7222`.
So command will be similar to below..
```
zfs set io.openebs:targetip=10.104.29.98  cstor-1d7bf36e-944f-447b-b27b-e3f7c4df7222/pvc-bea6c119-7abc-478a-a680-bc5a3db180ec
``

**Comment by cortopy** [comment]
Thanks both for your help!! No wonder I could not follow the instructions. My output is very different to what you guys are getting:

After doing the restore I get this for the list of pods:

```
+ kubectl get pods -n openebs
NAME                                                             READY   STATUS    RESTARTS   AGE
cstor-loop-pool-7zmx-64865588b4-vlpvh                            3/3     Running   0          4d6h
cstor-loop-pool-job6-565f9898f4-t478r                            3/3     Running   2          4d6h
openebs-admission-server-8695fd778c-rr672                        1/1     Running   0          4d6h
openebs-apiserver-657c6955cd-df8m4                               1/1     Running   0          4d6h
openebs-localpv-provisioner-7bf46f87d6-wpd5m                     1/1     Running   8          2d19h
openebs-ndm-7zxx2                                                1/1     Running   2          4d6h
openebs-ndm-cj546                                                1/1     Running   2          4d6h
openebs-ndm-operator-576fdfc88f-swtq5                            1/1     Running   0          4d6h
openebs-provisioner-664b96f6fd-qkwss                             1/1     Running   4          4d6h
openebs-snapshot-operator-6f6966895c-wpn9w                       2/2     Running   1          2d19h
pvc-40b95312-a7ab-4449-bec1-d78af9844363-target-bbcf44b4-hzhkh   3/3     Running   1          3m19s

```

I don't quite get why I have two deployments for the same cstor pool and you only have one ((I only have one pool in the cluster) ).

If I go into the first pod, I get this:

```
root@cstor-loop-pool-7zmx-64865588b4-vlpvh:/# zfs list
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc                                           4.05M  9.62G   512B  /cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc
cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc/pvc-40b95312-a7ab-4449-bec1-d78af9844363  2.63M  9.62G  2.63M  -

root@cstor-loop-pool-7zmx-64865588b4-vlpvh:/# zfs set io.openebs:targetip=10.96.93.78 cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc/pvc-40b95312-a7ab-4449-bec1-d78af9844363

root@cstor-loop-pool-7zmx-64865588b4-vlpvh:/# zfs list
NAME                                                                                                USED  AVAIL  REFER  MOUNTPOINT
cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc                                                         4.05M  9.62G   512B  /cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc
cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc/pvc-40b95312-a7ab-4449-bec1-d78af9844363                2.63M  9.62G  2.63M  -
cstor-adb90924-86b2-4f44-84f2-be6acdd1c3fc/pvc-40b95312-a7ab-4449-bec1-d78af9844363_rebuild_clone     0B  9.62G  2.63M  -
```

That "rebuild clone" looked very suspicious to me, and indeed the volume would not get mounted to the pod.

When I went into the second 

```
root@cstor-loop-pool-job6-565f9898f4-t478r:/# zfs list
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
cstor-1f171fea-4b76-4916-b57f-ee34a834c5f9                                           4.65M  9.62G   512B  /cstor-1f171fea-4b76-4916-b57f-ee34a834c5f9
cstor-1f171fea-4b76-4916-b57f-ee34a834c5f9/pvc-40b95312-a7ab-4449-bec1-d78af9844363  2.63M  9.62G  2.63M  -

root@cstor-loop-pool-job6-565f9898f4-t478r:/# zfs set io.openebs:targetip=10.96.93.78 cstor-1f171fea-4b76-4916-b57f-ee34a834c5f9/pvc-40b95312-a7ab-4449-bec1-d78af9844363

root@cstor-loop-pool-job6-565f9898f4-t478r:/# zfs list
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
cstor-1f171fea-4b76-4916-b57f-ee34a834c5f9                                           4.20M  9.62G   512B  /cstor-1f171fea-4b76-4916-b57f-ee34a834c5f9
cstor-1f171fea-4b76-4916-b57f-ee34a834c5f9/pvc-40b95312-a7ab-4449-bec1-d78af9844363  2.69M  9.62G  2.63M  -
```

And this one worked!

So if someone else lands here, this is what (I think) happened:

- the cstor pool name may have nothing to do with the cstor pool name in the deployment or the `name` itself of the CstorPool resource
- some resources may keep lingering with storage policy of Retain (I also discovered that deleting the volume was not enough. I also had to delete the CstorVolume). This part still confuses me a lot, as cleaning resources involves deleting PV, CstorVolume, CstorReplicas and Services. All manually
- `zfs list` is the key here

**Comment by mynktl** [comment]
Thanks for the feedback @cortopy .
I'm glad that you are able to restore the volume successfully. Recently we have added cloning feature, through which you can clone the existing workload to different namespace. Feel free to give it a try.

Regarding cstor storage engin, Request you to visit https://docs.openebs.io/docs/next/cstor.html. It has detailed information about cstor engine and its capabilities.
