### ISSUE TITLE
Panic when deleting snapshot that failed

### ISSUE THREAD

**Issue by cortopy** [openebs/velero-plugin#78]
**What steps did you take and what happened:**
- `velero backup create monitor --include-namespaces=monitor --snapshot-volumes`
- wait for backup to complete (snapshot fails)
- `velero backup delete monitor`

**What did you expect to happen:**
Plugin doesn't panic and allows velero to clean resources

**The output of the following commands will help us better understand what's going on**:

This is the info about the backup after trying to delete:

```
Name:         monitor
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Deleting

Namespaces:
  Included:  monitor
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-05-05 23:29:22 +0200 CEST
Completed:  2020-05-05 23:31:10 +0200 CEST

Expiration:  2020-06-04 23:29:22 +0200 CEST

Persistent Volumes:  0 of 1 snapshots completed successfully (specify --details for more information)

Deletion Attempts (1 failed):
  2020-05-05 23:34:43 +0200 CEST: Processed
  Errors:
    error deleting snapshot : rpc error: code = Aborted desc = plugin panicked: runtime error: index out of range

```
The logs for this particular backup are not available, as doing `velero backup describe monitor` returns

```
Logs for backup "monitor" are not available until it's finished processing. Please wait until the backup has a phase of Completed or Failed and try again.
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Velero version 1.3.2
- Velero features <NOT SET>
- Velero-plugin version 1.9.0
- OpenEBS version 1.9.1
- Kubernetes version 1.17.0
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): Ubuntu 18

**Comment by mynktl** [comment]
@cortopy Thanks for raising this issue. It seems velero is sending deletion request though snapshotID is empty. I've raised a fix in repo.
