### ISSUE TITLE
Support for Restore from Backup taken from old schema.

### ISSUE THREAD

**Issue by mynktl** [openebs/velero-plugin#82]
**Describe the problem/challenge you have**
This issue is about to restore the backup, taken from cstor v1alpha1, to cstor v1.

**Describe the solution you'd like**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Velero version (use `velero version`):
- Velero features (use `velero client config get features`):
- Velero-plugin version
- OpenEBS version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by kmova** [comment]
This needs to be included in the SPC to CSPC migration.

**Comment by nsathyaseelan** [comment]
- created SPC pool and cStor volume with old schema and taken the backup using minio bucket 
- Migrated the SPC pool to CSPC pool and Migrated the volume as well
- Post Migration Restore the Backup taken from the old schema.
- Restore was successful application is running and able to crate the data
